version: '3.8'

services:
  s3-storage:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - '4566'
    volumes:
      - './volumes/s3-storage/.init:/docker-entrypoint_initaws.d'
      - './volumes/s3-storage/.localstack:/tmp/localstack'
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - '5672:5672'
      - '15672:15672'
